Wurst-Imperium/Wurst-Client

Wurst Client/src/tk/wurst_client/Client.java
Wurst Client/src/tk/wurst_client/update/GuiUpdate.java
Wurst Client/src/tk/wurst_client/update/Updater.java

Added Updater

---

Wurst Client/src/tk/wurst_client/alts/Alt.java
Wurst Client/src/tk/wurst_client/files/FileManager.java
Wurst Client/src/tk/wurst_client/gui/alts/AltEditorScreen.java
Wurst Client/src/tk/wurst_client/gui/alts/EmailAllowedCharacters.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiAltAdd.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiAltEdit.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiAltList.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiAltLogin.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiAlts.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiEmailField.java

More AltManager enhancements

---

Wurst Client/src/tk/wurst_client/module/ModuleManager.java
Wurst Client/src/tk/wurst_client/module/modules/AutoArmor.java

Auto armor

---

Wurst Client/src/tk/wurst_client/module/ModuleManager.java
Wurst Client/src/tk/wurst_client/module/modules/NoSlowdown.java
patch/minecraft.patch

NoSlowdown

---

Wurst Client/src/tk/wurst_client/files/FileManager.java
Wurst Client/src/tk/wurst_client/spam/SpamProcessor.java
patch/minecraft.patch

Autorun wspam scripts

---

Wurst Client/src/tk/wurst_client/command/commands/AddAlt.java
Wurst Client/src/tk/wurst_client/command/commands/Annoy.java
Wurst Client/src/tk/wurst_client/command/commands/Binds.java
Wurst Client/src/tk/wurst_client/command/commands/Clear.java
Wurst Client/src/tk/wurst_client/command/commands/Drop.java
Wurst Client/src/tk/wurst_client/command/commands/Enchant.java
Wurst Client/src/tk/wurst_client/command/commands/FastBreakMod.java
Wurst Client/src/tk/wurst_client/command/commands/Features.java
Wurst Client/src/tk/wurst_client/command/commands/Friends.java
Wurst Client/src/tk/wurst_client/command/commands/GM.java
Wurst Client/src/tk/wurst_client/command/commands/Help.java
Wurst Client/src/tk/wurst_client/command/commands/IP.java
Wurst Client/src/tk/wurst_client/command/commands/NukerMod.java
Wurst Client/src/tk/wurst_client/command/commands/RV.java
Wurst Client/src/tk/wurst_client/command/commands/RenameForceOPEvenThoughTheNameIsTechnicallyCorrect.java
Wurst Client/src/tk/wurst_client/command/commands/Say.java
Wurst Client/src/tk/wurst_client/command/commands/SearchMod.java
Wurst Client/src/tk/wurst_client/command/commands/SpammerMod.java
Wurst Client/src/tk/wurst_client/command/commands/TP.java
Wurst Client/src/tk/wurst_client/command/commands/Taco.java
Wurst Client/src/tk/wurst_client/command/commands/ThrowMod.java
Wurst Client/src/tk/wurst_client/command/commands/Toggle.java
Wurst Client/src/tk/wurst_client/command/commands/VClip.java
Wurst Client/src/tk/wurst_client/command/commands/XRay.java

This new syntax is a mix of the Microsoft command-line syntax and the Git syntax.

Better command syntax

---

Wurst Client/src/tk/wurst_client/module/Module.java
Wurst Client/src/tk/wurst_client/module/ModuleManager.java
Wurst Client/src/tk/wurst_client/module/modules/PlayerFinder.java
Wurst Client/src/tk/wurst_client/utils/RenderUtils.java
patch/minecraft.patch

Finds far players during thunderstorms.
**Needs more tests!**
Resolves #113

PlayerFinder

---

Wurst Client/src/tk/wurst_client/command/ChatMessenger.java
Wurst Client/src/tk/wurst_client/command/CommandManager.java
Wurst Client/src/tk/wurst_client/command/commands/Nothing.java
Wurst Client/src/tk/wurst_client/command/commands/RV.java
Wurst Client/src/tk/wurst_client/command/commands/SpammerMod.java
Wurst Client/src/tk/wurst_client/command/commands/Toggle.java
Wurst Client/src/tk/wurst_client/command/commands/WMS.java
Wurst Client/src/tk/wurst_client/spam/SpamProcessor.java

- `.nothing`
- `.spammer spam <file>`
- `.t <mod> [(on | off)]`
- `.wms`

Spammer utility commands

---

Wurst Client/src/tk/wurst_client/gui/alts/GuiAltList.java
Wurst Client/src/tk/wurst_client/gui/alts/GuiAlts.java

Import Alts button

---

Wurst Client/src/tk/wurst_client/mod/ModManager.java
Wurst Client/src/tk/wurst_client/mod/mods/AntiPotion.java

AntiPotion

---

Wurst Client/src/tk/wurst_client/command/Command.java
Wurst Client/src/tk/wurst_client/command/CommandManager.java
Wurst Client/src/tk/wurst_client/command/commands/FollowMod.java
Wurst Client/src/tk/wurst_client/command/commands/GoTo.java
Wurst Client/src/tk/wurst_client/command/commands/Help.java
Wurst Client/src/tk/wurst_client/command/commands/Jump.java
Wurst Client/src/tk/wurst_client/command/commands/Path.java
Wurst Client/src/tk/wurst_client/command/commands/ProtectMod.java
Wurst Client/src/tk/wurst_client/command/commands/TP.java
Wurst Client/src/tk/wurst_client/mod/mods/Follow.java
Wurst Client/src/tk/wurst_client/mod/mods/Protect.java

New commands:
- `.follow`
- `.protect`
Commands that now support relative positions:
- `.goto`
- `.path`
- `.tp`

Movement commands

---

Wurst Client/src/tk/wurst_client/Client.java
patch/minecraft.patch

So yeah, there were some issues with Google Analytics.
On the bright side, Google Analytics helped me to improve Wurst by helping me to fix these issues.

Analytics fixes

---

Wurst Client/src/tk/wurst_client/commands/Cmd.java
Wurst Client/src/tk/wurst_client/commands/CmdManager.java
Wurst Client/src/tk/wurst_client/commands/DamageCmd.java

And add isNumeric() mehod to know if the string is numeric.
Well I find a method from am0d hacked client to damages you in **multiplayer only**.
The amount of damage goes trough 0 and 40.

Add Damage Command

---

Wurst Client/src/tk/wurst_client/mods/AutoWalkMod.java
Wurst Client/src/tk/wurst_client/mods/RemoteViewMod.java

These fixes are stupidly simple, but is always good to close an issue.

2 Simple Fixes

---

Wurst Client/src/tk/wurst_client/commands/TCmd.java

Now, it will not create "multi listeners".

Fix for #947

---

Wurst Client/src/tk/wurst_client/mods/FlightMod.java
Wurst Client/src/tk/wurst_client/mods/JetpackMod.java

I confused jesus and jetpack. Thats why i updated flight 2 times.

Flight + Jetpack = :( #1011 FIX

---

Wurst Client/src/tk/wurst_client/WurstClient.java

I hope this helps you to develop and publish 2.2 faster.

Change version to 2.2

---

Wurst Client/src/tk/wurst_client/gui/GuiManager.java

Remove WIP

---

Wurst Client/src/tk/wurst_client/commands/CmdManager.java
Wurst Client/src/tk/wurst_client/commands/GiveCmd.java

Created a .give command to get custom items in creative

---

Wurst Client/src/tk/wurst_client/mods/SpammerMod.java

Fix broken link in Spammer

---

Wurst updater/src/tk/wurst_client/updater/Main.java

Typo? (I think)

---

Wurst Client/src/tk/wurst_client/commands/BlinkCmd.java
Wurst Client/src/tk/wurst_client/mods/BlinkMod.java

2 fixes and distance traveled is now displayed.

Blink enhancement

---

Wurst Client/src/tk/wurst_client/commands/CmdManager.java
Wurst Client/src/tk/wurst_client/commands/ModifyCmd.java

It features 4 actions: add, remove, set and metadata.
Resolves #1946

Add .modify command

---

Wurst Client/src/tk/wurst_client/commands/CmdManager.java
Wurst Client/src/tk/wurst_client/commands/CopyItemCmd.java

Can copy any item from someone's hand or armor in creative, very useful for raid.

Copyitem Cmd

---

README.md

Fix 2 empty links
Fix download.wurst-client.tk doesn't work

Improve links

---

Wurst Client/src/tk/wurst_client/commands/LeaveCmd.java
Wurst Client/src/tk/wurst_client/mods/AutoLeaveMod.java

**The modes:**
- TP: Teleports you out of the world border. Does not work with NCP.
- SelfHurt: Tries to hit yourself. Bypasses NCP!

Added 2 new AutoLeave/.leave modes
